packages:
  - workflow
  - model
  - ui
  - block

catalog:
  '@platforma-sdk/model': ^1.23.0
  '@platforma-sdk/ui-vue': ^1.23.2
  '@platforma-sdk/workflow-tengo': ^5.3.3
  '@platforma-sdk/block-tools': ^2.6.14
  '@platforma-sdk/test': ^1.44.7
  '@platforma-sdk/tengo-builder': ^2.3.0
  '@platforma-open/milaboratories.software-blast': ^1.2.1
  
  'vue': ^3.5.13
  'vue-tsc': ^2.0.29
  
  'typescript': ^5.5.4
  'tsup': ~8.1.2
  'turbo': ^2.3.3

  'vite': ^5.3.5
  'vitest': ^2.0.4
  '@vitejs/plugin-vue': ^5.1.0

  '@changesets/cli': ^2.28.1
